name: Autofix Pull Requests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

jobs:
  if-pr-was-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

  checkout-repository:
    needs: if-pr-was-merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            show-progress: true
            lfs: false

  run-pre-commit:
    needs: checkout-repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
            architecture: 'x64'
      - run: |
            pip install pre-commit
            pre-commit run --all

  push-changes:
    needs: run-pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            show-progress: true
            lfs: false
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor_id }}+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Formatted code with pre-commit post pr ${{ github.event.number }}"
          git push
