name: Package Project

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            show-progress: true
            lfs: false
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'
            architecture: 'x64'

      - run: |
          make create-dev
          source env/bin/activate
          make build

  release-project:
    needs: build-project
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/ip2email
